dbt_elt:
  outputs:
    dev:
      account: IIELRIZ-HR09944
      database: SEGUROS
      password: Bagualjimmy23@
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: RENATAARAUJOE
      warehouse: COMPUTE_WH
  target: dev
